const tools_data = [
    {
        name: "RSA Encryption Demo",
        icon: "🔐",
        description: "Hands on experience on how RSA encryption is useful for privacy.",
        isDeprecated: false,
        isInProgress: false,
        isDisabled: false,
        link: "/RSAEncryption/RSAEncryption.html",
        target: "",
    },
    {
        name: "Live CCTV",
        icon: "📹",
        description: "Browse live public CCTV feeds from publicly available streams on the internet.",
        isDeprecated: false,
        isInProgress: false,
        isDisabled: false,
        link: "/cctv/cctv_services.html",
        target: "",
    },
    {
        name: "Live IP TV",
        icon: "📺",
        description: "Browse and streams publicly available IP TV on the internet.",
        isDeprecated: false,
        isInProgress: false,
        isDisabled: false,
        link: "/iptv/iptv.html",
        target: "",
    },
    {
        name: "Simple Downloader",
        icon: "📩",
        description: "Download videos and musics",
        isDeprecated: false,
        isInProgress: true,
        isDisabled: true,
        link: "/InstagramDownloader/instagram_downloader.html",
        target: "",
    },
    {
        name: "Voice Calculator",
        icon: "🎙️",
        description: "Speak your math — voice-controlled calculator.",
        isDeprecated: true,
        isInProgress: false,
        isDisabled: true,
        link: "/KalkulatorSuara/VoiceCalculator.html",
        target: "",
    },
    {
        name: "API Services",
        icon: "⚡",
        description: "A set of small backend APIs exposed for testing and use.",
        isDeprecated: true,
        isInProgress: false,
        isDisabled: true,
        link: "/API/api_services.html",
        target: "",
    },
    {
        name: "Live Chat Mock",
        icon: "💬",
        description: "Real-time chat prototype.",
        isDeprecated: false,
        isInProgress: true,
        isDisabled: true,
        link: "#",
        target: "",
    }
];